services:
  db: 
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: post
      POSTGRES_PASSWORD: gres
      

volumes:
  pgdata: